# 如果您来自bash，则可能必须更改 $PATH。
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# oh-my-zsh安装的路径。
ZSH=/usr/share/oh-my-zsh/

# 设置要加载的主题名称---如果设置为“random”，则每次加载 oh-my-zsh 时都会加载随机主题，
# 在这种情况下，要知道加载了哪个特定主题，运行：echo $RANDOM_THEME
# 参见 https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="amuse"

# 设置随机加载时可以选择的主题列表
# 在 ZSH_THEME=random 时设置此变量将导致zsh从此变量加载主题，而不是查看 $ZSH/themes/
# 如果设置为空数组，则此变量无效。
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# 取消注释以下行以启用大小写敏感。
# CASE_SENSITIVE="true"

# 取消注释以下行以使用对连字符不敏感的补全。
# 大小写敏感必须关闭。_和-将可以互换。
# HYPHEN_INSENSITIVE="true"

# 取消注释以下行以禁用每两周一次的自动更新检查。
# DISABLE_AUTO_UPDATE="true"

# 取消注释以下行以自动更新而不提示。
DISABLE_UPDATE_PROMPT="true"

# 取消注释以下行以更改自动更新的频率（以天为单位）。
# export UPDATE_ZSH_DAYS=13

# 如果粘贴URL和其他文本不正确，请取消注释以下行。
# DISABLE_MAGIC_FUNCTIONS="true"

# 取消注释以下行以禁用ls中的颜色。
# DISABLE_LS_COLORS="true"

# 取消注释以下行以禁用自动设置终端标题。
# DISABLE_AUTO_TITLE="true"

# 取消注释以下行以启用命令自动更正。
# ENABLE_CORRECTION="true"

# 在等待完成时，取消注释以下行以显示红点。
# COMPLETION_WAITING_DOTS="true"

# 如果要禁用将VCS下未跟踪的文件标记为脏文件，请取消注释以下行。
# 这使得对大型存储库的存储库状态检查变得非常快。
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# 如果要更改历史命令输出中显示的命令执行时间戳，请取消注释以下行。
# 您可以设置三种可选格式之一：
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# 或使用strftime函数格式规范设置自定义格式，有关详细信息，请参见“man strftime”。
# HIST_STAMPS="mm/dd/yyyy"

# 您是否要使用 $ZSH/custom 以外的其他自定义文件夹？
# ZSH_CUSTOM=/path/to/new-custom-folder

# 您要加载哪些插件？
# 标准插件可以在 $ZSH/plugins/ 中找到
# 自定义插件可以添加到 $ZSH_CUSTOM/plugins/
# 格式范例：plugins=(rails git textmate ruby lighthouse)
# 明智地添加，因为太多的插件会减慢Shell启动的速度。
plugins=(git)


# 用户配置

# export MANPATH="/usr/local/man:$MANPATH"

# 您可能需要手动设置语言环境
# export LANG=en_US.UTF-8

# 本地和远程会话的首选编辑器
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='nvim'
# else
#   export EDITOR='vim'
# fi

# 编译标志
# export ARCHFLAGS="-arch x86_64"

# 设置个人别名，覆盖oh-my-zsh库，插件和主题提供的别名。
# 可以在此处放置别名，尽管鼓励oh-my-zsh用户在ZSH_CUSTOM文件夹中定义别名。
# 要获取激活别名的完整列表，请运行`alias`。
#
# 别名示例
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias la='ls -a'
alias nn='nnn -P y'
alias nm='nm-connection-editor'
alias up='sudo pacman -Syu'
alias vi='nvim'

ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi

source $ZSH/oh-my-zsh.sh
